In [105]:
import pandas as pd
import numpy as np


#BASE_DIR = Path(r"C:\Users\Andrea\Downloads\NAPO_preliminar") #Usar cuando trabajo desde PC personal.

import os
from pathlib import Path

#BASE_DIR = Path(r"C:\Users\Andrea\Downloads\NAPO_preliminar") #Usar cuando trabajo desde PC personal.

BASE_DIR = Path(r"C:\Users\selene.baez\Downloads\NAPO_preliminar") #Usar cuando trabajo desde PC trabajo.
assert BASE_DIR.exists(), "La ruta no existe"
os.chdir(BASE_DIR)
print(Path.cwd()) 
print(BASE_DIR)

C:\Users\selene.baez\Downloads\NAPO_preliminar
C:\Users\selene.baez\Downloads\NAPO_preliminar

## Loja controles datos

Una sola base de datos para unir con la otra base. 
Aqui falta trabajar los IDs creo que estan solo los IDs nuevos, pero eso hay que revisar bien para ver las coincidencias

In [106]:
### config, encontrar una manera que sea un solo documento
named13C_cellulose = "δ13C (‰ v.s.V-PDB)"
named13C_bulk = "bulk_δ13C (‰ v.s.V-PDB)"
name18O = "δ18O in ‰ vs DeltaSMOW"
named15N = "δ15N (‰ v.s. V-PDB)"
nameC_bulk ="[C_b]%"
nameC_cellulose = "[C]%"
thick = "mean_thickness_(mm)"
though = "mean_toughness_(kN/m)"
LA = "Leaf area (cm²)"
name = "genus" + "especie"
ID = "Sample-ID"

In [107]:
rasgos_2024 = pd.read_excel(r"C:\Users\selene.baez\Downloads\NAPO_preliminar\SF_CONTROL\data_for_R.xlsx")
#cambiar nombres de columnas para que quede bien 
rasgos_2024_controles = rasgos_2024[rasgos_2024["Sub"]=="C"]
rasgos_2024_controles["Year"] = 2024

rasgos_2024_controles.sort_values(by="Plot")### Solo 2024.
#en rasgos solo mantener las columnas de los rasgos.

C:\Users\selene.baez\AppData\Local\Temp\ipykernel_5796\20011820.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rasgos_2024_controles["Year"] = 2024

,Unnamed: 0,Plot,TreeID,Sub,name,genus,specie,Site,[C_b],bulk_δ13C (‰ v.s.V-PDB),...,LPC,N_area,C_area,P_area,LA,C:P,N:P,N,P,Year
0,0,1,1608,C,Weinmania loxensis,Weinmania,loxensis,CaNu,0.448019,-29.445403,...,0.586049,1.583412,62.678630,0.081989,1.215139,764.474297,19.312442,0,0,2024
162,170,1,92,C,Alchornea lojaensis,NaN,Alchornea lojaensis,SFNu,0.498364,-28.200675,...,0.732131,3.580329,155.139517,0.227911,16.110000,680.703451,15.709357,0,0,2024
143,150,1,90,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.487816,-30.854881,...,0.324985,2.545161,141.426115,0.094219,17.763700,1501.042394,27.013355,0,0,2024
140,147,1,96,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.467702,-33.285472,...,0.360224,2.277284,102.445748,0.078904,20.612600,1298.365099,28.861575,0,0,2024
135,142,1,5812,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.474813,-30.184038,...,0.330146,2.808968,147.344794,0.102451,18.368050,1438.191984,27.417563,0,0,2024
112,117,1,69,C,Alchornea lojaensis,NaN,Alchornea lojaensis,SFNu,0.493337,-29.756254,...,0.733031,3.326850,128.510592,0.190949,31.133350,673.010484,17.422729,0,0,2024
166,174,1,101,C,Alchornea lojaensis,NaN,Alchornea lojaensis,SFNu,0.491481,-29.736809,...,0.788999,3.145972,117.900075,0.189271,57.610350,622.916971,16.621526,0,0,2024
85,89,1,9096,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.470921,-31.778506,...,0.362506,2.747689,124.133947,0.095556,17.469750,1299.069369,28.754737,0,0,2024
83,87,1,88,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.461137,-30.893770,...,0.302269,2.273111,134.993606,0.088486,23.877800,1525.586490,25.688825,0,0,2024
55,58,1,19003,C,Hedyosmun purpurascens,Hedyosmun,purpurascens,CaNu,0.432270,-30.631127,...,0.905815,1.640719,46.204400,0.096821,20.208092,477.216224,16.945955,0,0,2024
172,180,1,9091,C,Alchornea lojaensis,NaN,Alchornea lojaensis,SFNu,0.499427,-29.629863,...,0.886819,3.227764,127.135192,0.225750,28.342800,563.166956,14.297931,0,0,2024
2,2,1,5861,C,Weinmania loxensis,Weinmania,loxensis,CaNu,0.453564,-29.504389,...,0.586801,1.459443,62.014105,0.080231,1.316500,772.943881,18.190504,0,0,2024
16,16,4,2048,C,Pouteria torta,Pouteria,torta,BoN,0.483866,-33.402050,...,0.733080,2.199749,64.181048,0.097237,89.979000,660.045948,22.622490,0,0,2024
17,17,4,2060,C,Pouteria torta,Pouteria,torta,BoN,0.466924,-34.803301,...,0.692635,1.804096,48.111207,0.071368,81.183200,674.127256,25.278731,0,0,2024
18,18,4,2062,C,Pouteria torta,Pouteria,torta,BoN,0.489575,-32.605411,...,0.549719,2.216437,68.165106,0.076539,68.123100,890.591188,28.958207,0,0,2024
20,20,5,1012,C,Weinmania loxensis,Weinmania,loxensis,CaNu,0.432495,-28.636900,...,0.472760,1.359691,72.098696,0.078811,1.559650,914.830509,17.252558,0,0,2024
22,22,5,19006,C,Hedyosmun purpurascens,Hedyosmun,purpurascens,CaNu,0.438016,-28.158286,...,0.907596,2.083919,64.502693,0.133653,17.825503,482.611332,15.591956,0,0,2024
21,21,5,1014,C,Weinmania loxensis,Weinmania,loxensis,CaNu,0.441728,-29.332075,...,0.541857,1.532285,58.814773,0.072147,1.727414,815.211391,21.238478,0,0,2024
106,110,7,356,C,Alchornea lojaensis,NaN,Alchornea lojaensis,SFNu,0.494209,-28.628459,...,0.733029,3.515637,153.421616,0.227561,31.713150,674.200098,15.449210,0,0,2024
163,171,7,335,C,Alchornea lojaensis,NaN,Alchornea lojaensis,SFNu,0.483675,-29.950701,...,0.713518,2.714434,123.772271,0.182589,34.114900,677.872686,14.866337,0,0,2024
161,169,7,6994,C,Alchornea lojaensis,NaN,Alchornea lojaensis,SFNu,0.485233,-29.260413,...,0.876008,3.060134,116.550839,0.210413,20.733100,553.914092,14.543449,0,0,2024
144,151,7,341,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.468266,-31.243776,...,0.419116,2.076559,128.140329,0.114691,18.344700,1117.270370,18.105763,0,0,2024
142,149,7,6992,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.464434,-31.370166,...,0.443659,1.934834,121.974024,0.116518,12.527150,1046.824745,16.605442,0,0,2024
136,143,7,333,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.468304,-31.117385,...,0.409006,2.748330,137.751075,0.120309,13.615550,1144.979613,22.843975,0,0,2024
87,91,7,7994,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.474632,-30.456264,...,0.354788,2.205906,134.610877,0.100622,19.480900,1337.789611,21.922732,0,0,2024
41,44,8,1930,C,Clarisia racemosa,Clarisia,racemosa,BoN,0.404803,-31.568413,...,0.739227,1.803572,49.813590,0.090966,29.620600,547.603859,19.826782,0,0,2024
42,45,8,1942,C,Pouteria torta,Pouteria,torta,BoN,0.479747,-33.313238,...,0.891906,1.563234,49.415609,0.091870,68.978200,537.889115,17.015809,0,0,2024
43,46,8,7546,C,Pouteria torta,Pouteria,torta,BoN,0.472916,-33.115879,...,0.736298,1.727182,56.276081,0.087618,82.270250,642.288440,19.712626,0,0,2024
39,39,8,1925,C,Pouteria torta,Pouteria,torta,BoN,0.480826,-34.122411,...,0.631807,1.962294,64.069935,0.084188,48.555450,761.032976,23.308438,0,0,2024
40,43,8,1927,C,Pouteria torta,Pouteria,torta,BoN,0.552969,-32.731028,...,0.519643,2.080348,NaN,0.068323,68.717300,NaN,30.448723,0,0,2024
50,53,10,19011,C,Hedyosmun purpurascens,Hedyosmun,purpurascens,CaNu,0.443493,-27.410451,...,0.737201,2.700332,92.268082,0.153374,18.168846,601.590530,17.606241,0,0,2024
52,55,10,5819,C,Weinmania loxensis,Weinmania,loxensis,CaNu,0.444585,-28.816381,...,0.608936,1.485072,62.792708,0.086006,1.522243,730.100608,17.267160,0,0,2024
65,69,12,7626,C,Pouteria torta,Pouteria,torta,BoN,0.475263,-33.762179,...,0.459120,2.245349,63.852611,0.061684,62.001200,1035.159194,36.400915,0,0,2024
160,168,12,7594,C,Alchornea lojaensis,NaN,Alchornea lojaensis,SFNu,0.498274,-28.084007,...,1.060681,3.857753,156.769411,0.333717,24.139850,469.767851,11.559963,0,0,2024
63,67,12,2176,C,Clarisia racemosa,Clarisia,racemosa,BoN,0.429151,-32.615382,...,0.824084,1.729739,41.692610,0.080061,35.099850,520.761003,21.605283,0,0,2024
64,68,12,6007,C,Pouteria torta,Pouteria,torta,BoN,0.430295,-34.514266,...,0.535752,1.653303,NaN,0.068092,113.653550,NaN,24.280324,0,0,2024
141,148,12,729,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.471274,-30.786824,...,0.389493,2.391203,149.040709,0.123177,20.347800,1209.968470,19.412683,0,0,2024
86,90,12,721,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.464322,-32.799354,...,0.484951,2.638257,114.464407,0.119550,28.273600,957.460565,22.068232,0,0,2024
134,141,12,708,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.476319,-31.272943,...,0.433246,2.769313,134.283682,0.122141,18.640050,1099.417301,22.673122,0,0,2024
126,133,12,4894,C,Alchornea lojaensis,NaN,Alchornea lojaensis,SFNu,0.493496,-28.929853,...,0.828567,3.422024,153.648757,0.257972,21.390900,595.602050,13.265088,0,0,2024
70,74,14,19017,C,Hedyosmun purpurascens,Hedyosmun,purpurascens,CaNu,0.444777,-29.115515,...,0.781730,2.020516,66.138294,0.116243,17.148639,568.965057,17.381810,0,0,2024
71,75,14,19018,C,Hedyosmun purpurascens,Hedyosmun,purpurascens,CaNu,0.431527,-28.098459,...,0.844439,2.290004,63.798566,0.124845,16.774461,511.021653,18.342759,0,0,2024
72,76,14,3011,C,Clarisia racemosa,Clarisia,racemosa,BoN,0.430161,-32.485757,...,0.815837,2.143935,46.772540,0.088708,53.663800,527.264133,24.168457,0,0,2024
139,146,17,4932,C,Alchornea lojaensis,NaN,Alchornea lojaensis,SFNu,0.469234,-28.336788,...,0.629966,3.389107,126.819095,0.170260,34.835750,744.855587,19.905483,0,0,2024
148,155,17,4933,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.468709,-30.106259,...,0.423162,2.615745,145.456853,0.131322,14.129900,1107.635699,19.918569,0,0,2024
132,139,17,902,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.497760,-30.329873,...,1.034293,NaN,155.634565,0.323392,18.214100,481.256233,NaN,0,0,2024
96,100,17,7645,C,Alchornea lojaensis,NaN,Alchornea lojaensis,SFNu,0.478014,-28.064562,...,0.612590,2.369267,148.213911,0.189941,38.250400,780.315997,12.473706,0,0,2024
89,93,17,881,C,Alchornea lojaensis,NaN,Alchornea lojaensis,SFNu,0.494485,-30.417375,...,0.751182,3.639815,162.100517,0.246250,21.124600,658.275848,14.780966,0,0,2024
93,97,17,8954,C,Myrcia sp nov,NaN,Myrcia sp nov,SFNu,0.469073,-32.634074,...,0.435003,1.937192,108.080729,0.100230,38.517750,1078.322629,19.327388,0,0,2024

# Muestras de 2009 controles.

In [108]:
#old tree ID = treeID
#new tree ID = TreeID
#
samples_SF = pd.read_excel(r"C:\Users\selene.baez\Downloads\NAPO_preliminar\SF_control\SanFranciscoNumex2011.xlsx")
samples_SF = samples_SF.rename(columns = {"sample":"sample ID","site":"Site","tree#":"tree ID"})
samples_SF["Year"]= "2011"
samples_SF["sample ID"] = "46"+samples_SF["sample ID"].astype("str") #46 al inicio de todas
samples_SF["sample ID"] = samples_SF["sample ID"].replace({"4694":"46094","4697":"46097","4693":"46093"})
samples_SF["Site"] = "SFNu"

samples_CaNU_BoNU = pd.read_excel(BASE_DIR/"SF_controL"/"Samples_NUMEX2009.xlsx")
samples_CaNU_BoNU["Year"] = "2009"
samples_CaNU_BoNU = samples_CaNU_BoNU.rename(columns={"Site ":"Site"}) #elimina el espacio presente
samples_2009 = pd.concat([samples_SF,samples_CaNU_BoNU])
samples_2009

,sample ID,Site,plot,treatment,tree ID,species,Bezeichnung,Year
0,46094,SFNu,1,C,69,Alchornea lojaensis,SF-C1-69-2011,2011
1,46097,SFNu,1,C,109,Alchornea lojaensis,SF-C1-109-2011,2011
2,46142,SFNu,7,C,334,Alchornea lojaensis,SF-C7-334-2011,2011
3,46143,SFNu,7,C,335,Alchornea lojaensis,SF-C7-335-2011,2011
4,46186,SFNu,12,C,713,Alchornea lojaensis,SF-C12-713-2011,2011
5,46189,SFNu,12,C,714,Alchornea lojaensis,SF-C12-714-2011,2011
6,46229,SFNu,17,C,881,Alchornea lojaensis,SF-C17-881-2011,2011
7,46237,SFNu,17,C,882,Alchornea lojaensis,SF-C17-882-2011,2011
8,46093,SFNu,1,C,68,Myrcia sp.,SF-C1-68-2011,2011
9,46144,SFNu,7,C,341,Myrcia sp.,SF-C7-341-2011,2011
10,46145,SFNu,7,C,351,Myrcia sp.,SF-C7-351-2011,2011
11,46152,SFNu,7,C,337,Myrcia sp.,SF-C7-337-2011,2011
12,46185,SFNu,12,C,708,Myrcia sp.,SF-C12-708-2011,2011
13,46232,SFNu,17,C,902,Myrcia sp.,SF-C17-902-2011,2011
0,2009-0107,BoNu,12,C,2176,Clarisia racemosa,NaN,2009
1,2009-0109,BoNu,14,C,3011,Clarisia racemosa,NaN,2009
2,2009-0120,BoNu,4,C,2048,Pouteria torta,NaN,2009
3,2009-0121,BoNu,4,C,2060,Pouteria torta,NaN,2009
4,2009-0122,BoNu,4,C,2062,Pouteria torta,NaN,2009
5,2009-0128,BoNu,8,C,1925,Pouteria torta,NaN,2009
6,2009-0129,BoNu,8,C,1927,Pouteria torta,NaN,2009
7,2009-0130,BoNu,8,C,1931,Pouteria torta,NaN,2009
8,2009-0131,BoNu,8,C,1942,Pouteria torta,NaN,2009
9,2009-0132,BoNu,8,C,1949,Pouteria torta,NaN,2009
10,2009-0138,BoNu,12,C,2162,Pouteria torta,NaN,2009
11,2009-0139,BoNu,12,C,2164,Pouteria torta,NaN,2009
12,2009-0140,BoNu,12,C,2173,Pouteria torta,NaN,2009
13,2009-0151,CaNu,5,C,26,Hedyosmum sp.,NaN,2009
14,2009-0157,CaNu,10,C,12,Hedyosmum sp.,NaN,2009
15,2009-0163,CaNu,14,C,22,Hedyosmum sp.,NaN,2009
16,2009-0164,CaNu,14,C,23,Hedyosmum sp.,NaN,2009
17,2009-0167,CaNu,1,C,1602,Weinmannia loxensis,NaN,2009
18,2009-0168,CaNu,1,C,1608,Weinmannia loxensis,NaN,2009
19,2009-0175,CaNu,5,C,1012,Weinmannia loxensis,NaN,2009
20,2009-0176,CaNu,5,C,1014,Weinmannia loxensis,NaN,2009
21,2009-0183,CaNu,10,C,1243,Weinmannia loxensis,NaN,2009
22,2009-0188,CaNu,14,C,3,Weinmannia loxensis,NaN,2009

# Celulosa 2006

In [109]:
#CELLULOSA
celulosa = pd.read_excel(r"C:\Users\selene.baez\Downloads\NAPO_preliminar\Results_isofys\Andrea-Cellulose-13C-202603.xlsx") #TODAVIA NO ME DAN LOS RESULTADOS
samples_list_CaBo = ["p09-0157","p09-0163","p09-0132","p09-0188","p09-183",
                     "p04-175","p09-0164","pxx-0124","p09-01343", "p09-0109",
                    "p09-0122","p09-0130","p09-139", "p09-151", "p09-131", 
                    "p09-120", "p09-138","p09-0128","p04-0129","p09-107",
                    "p09-168","p09-167","p09-176", ######muestras del 2011
                    46229, 46097,46143,46093,46185,46144,46237,46145,46232,46142,46094,"46186","46152"
                    ] #meti la pata en los nombres y les puse p09.

cel2026 = celulosa[celulosa["Sample-ID"].isin(samples_list_CaBo)]

cel2026["Sample-ID"] = cel2026["Sample-ID"].replace({
    "p09-0157":"2009-0157",
    "p09-0163":"2009-0163",
    "p09-0132":"2009-0132",
    "p09-0188":"2009-0188",
    "p09-183":"2009-0183",
    "p04-175":"2009-0175",
    "p09-0164":"2009-0164",
    "pxx-0124":"2009-0129", #### 0124 no existe.
    #"p09-01343", 
    "p09-0109":"2009-0109",
    "p09-0122":"2009-0122",
    "p09-0130":"2009-0130",
    "p09-139":"2009-0139",
    "p09-151":"2009-0151",
    "p09-131":"2009-0131",
    "p09-120": "2009-0120", "p09-138":"2009-0138",
    "p09-0128":"2009-0128","p04-0129":"2009-0129","p09-107":"2009-0107",
    "p09-168":"2009-0168","p09-167":"2009-0167","p09-176":"2009-0176"
})

cel2026["Sample-ID"] = cel2026["Sample-ID"].astype(str)
## 121 no hay, 

#HELP: Fijarse que hay unos tipos y tener cuidado de no mezclar con Sumaco. "PQ1"
#Luego unir resultados con la lista de arriba. Corregir los typos. 
cel2026ctrl = pd.merge(samples_2009,cel2026, left_on="sample ID",right_on= "Sample-ID", how="outer")
cel2026ctrl["sample ID"] = cel2026ctrl["sample ID"].combine_first(cel2026ctrl["Sample-ID"])
cel2026ctrl = cel2026ctrl.drop(columns=["treatment","nr of samples","Bezeichnung","Sample-ID"])

cel2026ctrl = cel2026ctrl.rename(columns={"[C] m/m in %":nameC_cellulose,"plot":"Plot","sample ID":ID,"tree ID":"old_treeID"
                                  })

cel2026ctrl
#hay unas muestras p09-183, y p09-0140 que tal vez son controles en NUMEX.SF

C:\Users\selene.baez\AppData\Local\Temp\ipykernel_5796\1959316654.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cel2026["Sample-ID"] = cel2026["Sample-ID"].replace({
C:\Users\selene.baez\AppData\Local\Temp\ipykernel_5796\1959316654.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cel2026["Sample-ID"] = cel2026["Sample-ID"].astype(str)

,Sample-ID,Site,Plot,old_treeID,species,Year,[C]%,δ13C (‰ v.s. V-PDB),Batch
0,46094,SFNu,1.0,69.0,Alchornea lojaensis,2011,51.020000,-26.960000,AndreaChavez-Sumaco-SEQ3-HF1-C - repro
1,46097,SFNu,1.0,109.0,Alchornea lojaensis,2011,49.738208,-25.990777,AndreaChavez-Sumaco-SEQ2-HF1-C - repro
2,46142,SFNu,7.0,334.0,Alchornea lojaensis,2011,48.805481,-26.141274,AndreaChavez-Sumaco-SEQ2-HF1-C - repro
3,46143,SFNu,7.0,335.0,Alchornea lojaensis,2011,49.398647,-27.058350,AndreaChavez-Sumaco-SEQ2-HF1-C - repro
4,46186,SFNu,12.0,713.0,Alchornea lojaensis,2011,48.355538,-24.989506,AndreaChavez-Sumaco-SEQ2-HF1-C - repro
5,46189,SFNu,12.0,714.0,Alchornea lojaensis,2011,NaN,NaN,NaN
6,46229,SFNu,17.0,881.0,Alchornea lojaensis,2011,45.680476,-25.804918,AndreaChavez-Sumaco-SEQ2-HF1-C - repro
7,46237,SFNu,17.0,882.0,Alchornea lojaensis,2011,48.166891,-27.686740,AndreaChavez-Sumaco-SEQ2-HF1-C - repro
8,46093,SFNu,1.0,68.0,Myrcia sp.,2011,43.501389,-28.270380,AndreaChavez-Sumaco-SEQ2-HF1-C - repro
9,46144,SFNu,7.0,341.0,Myrcia sp.,2011,44.155086,-26.660377,AndreaChavez-Sumaco-SEQ2-HF1-C - repro
10,46145,SFNu,7.0,351.0,Myrcia sp.,2011,43.628431,-27.839944,AndreaChavez-Sumaco-SEQ2-HF1-C - repro
11,46152,SFNu,7.0,337.0,Myrcia sp.,2011,43.708116,-26.966001,AndreaChavez-Sumaco-SEQ2-HF1-C - repro
12,46185,SFNu,12.0,708.0,Myrcia sp.,2011,43.954128,-26.699591,AndreaChavez-Sumaco-SEQ2-HF1-C - repro
13,46232,SFNu,17.0,902.0,Myrcia sp.,2011,43.999366,-27.493633,AndreaChavez-Sumaco-SEQ2-HF1-C - repro
14,2009-0107,BoNu,12.0,2176.0,Clarisia racemosa,2009,44.388543,-30.405111,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
15,2009-0109,BoNu,14.0,3011.0,Clarisia racemosa,2009,43.920529,-31.856766,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
16,2009-0120,BoNu,4.0,2048.0,Pouteria torta,2009,43.973681,-28.673371,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
17,2009-0121,BoNu,4.0,2060.0,Pouteria torta,2009,NaN,NaN,NaN
18,2009-0122,BoNu,4.0,2062.0,Pouteria torta,2009,44.472603,-29.728958,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
19,2009-0128,BoNu,8.0,1925.0,Pouteria torta,2009,44.217618,-29.883877,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
20,2009-0129,BoNu,8.0,1927.0,Pouteria torta,2009,44.458020,-30.477374,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
21,2009-0129,BoNu,8.0,1927.0,Pouteria torta,2009,44.523062,-32.076526,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
22,2009-0130,BoNu,8.0,1931.0,Pouteria torta,2009,45.171311,-30.596406,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
23,2009-0131,BoNu,8.0,1942.0,Pouteria torta,2009,48.816182,-31.310451,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
24,2009-0132,BoNu,8.0,1949.0,Pouteria torta,2009,45.925396,-32.676205,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
25,2009-0138,BoNu,12.0,2162.0,Pouteria torta,2009,NaN,NaN,NaN
26,2009-0139,BoNu,12.0,2164.0,Pouteria torta,2009,44.671330,-29.089247,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
27,2009-0140,BoNu,12.0,2173.0,Pouteria torta,2009,NaN,NaN,NaN
28,2009-0151,CaNu,5.0,26.0,Hedyosmum sp.,2009,44.427820,-23.988408,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
29,2009-0157,CaNu,10.0,12.0,Hedyosmum sp.,2009,45.524787,-25.043446,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
30,2009-0163,CaNu,14.0,22.0,Hedyosmum sp.,2009,46.438509,-28.063073,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
31,2009-0164,CaNu,14.0,23.0,Hedyosmum sp.,2009,40.342104,-25.510179,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
32,2009-0167,CaNu,1.0,1602.0,Weinmannia loxensis,2009,NaN,NaN,NaN
33,2009-0168,CaNu,1.0,1608.0,Weinmannia loxensis,2009,NaN,NaN,NaN
34,2009-0175,CaNu,5.0,1012.0,Weinmannia loxensis,2009,43.039298,-30.509274,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
35,2009-0176,CaNu,5.0,1014.0,Weinmannia loxensis,2009,NaN,NaN,NaN
36,2009-0183,CaNu,10.0,1243.0,Weinmannia loxensis,2009,43.157017,-26.481769,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
37,2009-0188,CaNu,14.0,3.0,Weinmannia loxensis,2009,43.392762,-27.462748,AndreaChavez-Sumaco-SEQ1-HF1-C - repro
38,p09-01343,NaN,NaN,NaN,NaN,NaN,45.390252,-29.755755,AndreaChavez-Sumaco-SEQ1-HF1-C - repro

# Nutrientes: C, N, delta15N.

In [110]:

#SEQ1= pd.read_excel(r"C:\Users\selene.baez\Downloads\NAPO_preliminar\Results_isofys\Andrea_bulk CN_2025.xlsx",sheet_name="SEQ1")
#SEQ1["Year"] = 2006

SEQ7 = pd.read_excel(r"C:\Users\selene.baez\Downloads\NAPO_preliminar\Results_isofys\Andrea_bulk CN_2025.xlsx",sheet_name="SEQ7")
SEQ7["Year"] = 2009 #segun yo es la unica secuencia util con resultados de isotopos de controles

bulk = SEQ7
bulk
bulk = bulk.rename(columns={"certified values":"sample-ID", "Unnamed: 2":"[N]",
                         "Unnamed: 4":nameC_bulk,"Unnamed: 6":named15N,
                          "Unnamed: 8":named13C_bulk})

columns_drop = ["Unnamed: 0", "Unnamed: 3","Unnamed: 5","Unnamed: 7", "Unnamed: 9"]

bulk = bulk.drop(columns=columns_drop)

patrones = ["p09"]# Seleccionamos solo los controles de 2009
df_filtrado_bulk = bulk[bulk["sample-ID"].str.contains("|".join(patrones), na=False)]
df_filtrado_bulk[["Plot2009","code","Year"]] =df_filtrado_bulk["sample-ID"].str.split("-",expand=True)
df_filtrado_bulk["sample-ID"] = "2009-" + df_filtrado_bulk["code"] ##reemplazamos ID por nombre correcto
df_filtrado_bulk = df_filtrado_bulk.drop(columns = {"Plot2009","Year","code"}) # el año igual lo añadimos despues
df_filtrado_bulk = df_filtrado_bulk.rename(columns={"sample-ID":"Sample-ID"})

## añadir informacion
#df_filtrado_bulk_info = pd.merge(df_filtrado_bulk,samples_CaNU_BoNU, left_on="sample-ID",right_on="sample ID")
#df_filtrado_bulk_info

C:\Users\selene.baez\AppData\Local\Temp\ipykernel_5796\2837750508.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado_bulk[["Plot2009","code","Year"]] =df_filtrado_bulk["sample-ID"].str.split("-",expand=True)
C:\Users\selene.baez\AppData\Local\Temp\ipykernel_5796\2837750508.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado_bulk[["Plot2009","code","Year"]] =df_filtrado_bulk["sample-ID"].str.split("-",expand=True)
C:\Users\selene.baez\AppData\Local\Temp\ipykernel_5796\2837750508.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado_bulk["sample-ID"] = "2009-" + df_filtrado_bulk["code"] ##reemplazamos ID por nombre correcto

# BUlk 2026 se añade

In [111]:
bulk_2026 = pd.read_excel(BASE_DIR/"Results_isofys"/"Andrea_bulk_CN_20260928.xlsx")
bulk_2026 = bulk_2026.rename(columns={"Sample ID":"Sample-ID", "[C]":nameC_bulk,"δ13C (‰ v.s.V-PDB)":named13C_bulk,"δ15N (‰ v.s.AIR)":named15N})
muestras_SF = [
    "46093-my",
    "46185-my",
    "46145-my",
    "46232-my",
    "46144-my",
    "46152-my",
    "46186-al",
    "46143-al",
    "46237-al",
    "46094-al",
    "46142-al",
    "46097-al",
    "46229-al",
    "46189-al",
    "56127", #medir nuevamente
    "56074", #medir nuevamente
    "56078", #medir nuevamente
 ]

# df es tu base de datos
df_filtrado = bulk_2026[bulk_2026["Sample-ID"].isin(muestras_SF)]
columns_drop = [ "Unnamed: 2","Unnamed: 5","Unnamed: 7", "Unnamed: 3","Unnamed: 9","Batch","Sample ID.1"]

df_filtrado = df_filtrado.drop(columns=columns_drop)
df_filtrado[["Sample-ID","species_code"]] = df_filtrado["Sample-ID"].str.split("-",expand=True)
df_filtrado

,Sample-ID,[N],[C_b]%,δ15N (‰ v.s. V-PDB),bulk_δ13C (‰ v.s.V-PDB),species_code
107,46093,0.008345,0.464492,-2.729912,-31.227959,my
108,46185,0.00923,0.473769,-3.685854,-29.893648,my
109,46145,0.008362,0.468842,-3.842004,-30.500654,my
110,46232,0.006583,0.47448,-3.797703,-30.352183,my
111,46144,0.007507,0.469399,-3.97435,-30.082505,my
112,46152,0.009309,0.475291,-3.028051,-30.055877,my
113,46186,0.012976,0.486353,-4.245768,-27.07889,al
114,46143,0.013631,0.493543,-4.171096,-28.59716,al
115,46237,0.010886,0.489575,-3.642355,-29.374751,al
116,46094,0.01211,0.488267,-4.794846,-28.110997,al
117,46142,0.012693,0.486461,-3.689435,-27.579523,al
118,46097,0.010593,0.493025,-4.41627,-27.104207,al
119,46229,0.008141,0.488411,-6.295312,-28.404006,al
120,46189,0.010691,0.491472,-4.539594,-27.430286,al

In [112]:
bulk = pd.concat([df_filtrado,df_filtrado_bulk])

In [113]:
ctrl = pd.merge(bulk,cel2026ctrl, on= ID ,how="outer")
ctrl = ctrl.rename(columns={"δ13C (‰ v.s. V-PDB)":named13C_cellulose,"species":"name","old_treeID":"TreeID",
                            "[C]%":nameC_cellulose,"δ15N (‰ v.s. V-PDB)":named15N,"treatment":"Sub"})
ctrl
#se actualizan los numeros de los arboles
ctrl["TreeID"] = ctrl["TreeID"].replace({
    1931: 7546,
    2162: 7626,
    2164: 7587,  # muerto
    2173: 6007,
    26: 19006,
    12: 19011,
    22: 19017,  
    23: 19018,  
    1602: 5861,
    1243: 5819
})

# NEXT: 
1. Concatenar entre 2009 y 2025.

In [120]:
rasgos_2024_controles = rasgos_2024_controles.rename(columns={"[C_b]":nameC_bulk,"δ15N (‰ v.s.AIR)":named15N,"[C]":nameC_cellulose})
rasgos_2024_controles = rasgos_2024_controles.drop(columns={"Year"}) #not accurate
rasgos_2024_controles = rasgos_2024_controles.rename(columns={"year":"Year"})

In [ ]:
NUMEXC_completo = pd.concat([rasgos_2024_controles,ctrl])
NUMEXC_completo['Site'] = NUMEXC_completo['Site'].replace('BoN', 'BoNu')
NUMEXC_completo['Site'] = NUMEXC_completo['Site'].replace("CaNu ","CaNu")
#HELP eliminar columnas que no vaya a usar.

In [ ]:
NUMEXC_completo.to_excel("NUMEXC_complete.xlsx")