In [76]:
import pandas as pd
import numpy as np
#from config_ import *

named13C_cellulose = "δ13C (‰ v.s.V-PDB)" ### Exceptional 
named13C_bulk = "bulk_δ13C (‰ v.s.V-PDB)"
name18O = "δ18O in ‰ vs DeltaSMOW"
named15N = "δ15N (‰ v.s. V-PDB)"
nameC_bulk ="[C_b]%"
nameC_cellulose = "[C]%"
thick = "mean_thickness_(mm)"
though = "mean_toughness_(kN/m)"
LA = "Leaf area (cm²)"
name = "genus" + "especie"

Galeras Cleaning

base_grandes =

rasgos =

#unir estas dos primero y tener unificado, asegurandonos que estamos bien
#unir con cellulosa y bulk

In [77]:
rasgos = pd.read_excel(r"C:\Users\selene.baez\Downloads\NAPO_preliminar\Galeras\03. Rasgos Galeras.xlsx")
#en rasgos solo mantener las columnas de los rasgos. 
rasgos = rasgos.rename(columns={"#":"Plot", "TreeID_2025":"TreeID"}) #Nunca usar Familia y genus de este.

# Resultados Julio 2025

In [78]:
#CELLULOSA
celulosa = pd.read_excel(r"C:\Users\selene.baez\Downloads\NAPO_preliminar\Galeras\resultados072025.xlsx")
patrones = ["p60", "p62", "p22","p23","p24","p28","p48","p50","p29"]
df_filtrado = celulosa[celulosa["Sample ID"].str.contains("|".join(patrones), na=False)]
## arreglando typos
df_filtrado["Sample ID"] = df_filtrado["Sample ID"].replace({
    "p28-8974": "p23-8974",
    "p28-8982": "p23-8982",
    "p28-8976": "p23-8976"})

df_filtrado["Year"] = np.select(
    [
        df_filtrado["Meas batch"].str.contains("NAPO2006", na=False),
        df_filtrado["Meas batch"].str.contains("NUMEX", na=False), #caso especial
        df_filtrado["Meas batch"].str.contains("NAPO2025", na=False),
    ],
    [2006,2006,2025],
    default=np.nan
)

import numpy as np
#HELP: La idea es filtrar y luego de filtrar por año se puede unir por ID 2025 o ID original
df_filtrado[["Plot","TreeID"]] = df_filtrado["Sample ID"].str.split("-",expand=True)
df_filtrado["Type"] = "leaf pulverized"
df_filtrado["Plot"]= df_filtrado["Plot"].str.replace("p","")
df_filtrado= df_filtrado.drop(columns={"Meas batch","Comment","Plot"})

def homogeneizar_ID(df):
  df["old_treeID"] = np.where(df["Year"] == 2006, df["TreeID"], np.nan)
  df["new_TreeID"] = np.where(df["Year"] == 2025, df["TreeID"], np.nan)
  return  df

df_filtrado = df_filtrado.rename(columns = {"δ15N (‰ v.s. AIR)":named13C_cellulose,"[C] in %":nameC_cellulose,"Sample ID":"Sample-ID"})
#df_filtrado = homogeneizar_ID(df_filtrado)
print("Resultados de Celulosa")
df_filtrado= df_filtrado.drop(columns = {"TreeID","Year"})

len(df_filtrado) #78
df_filtrado

Resultados de Celulosa

C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\2358179937.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado["Sample ID"] = df_filtrado["Sample ID"].replace({
C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\2358179937.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado["Year"] = np.select(
C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\2358179937.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado[["Plot","TreeID"]] = df_filtrado["Sample ID"].str.split("-",expand=True)
C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\2358179937.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado[["Plot","TreeID"]] = df_filtrado["Sample ID"].str.split("-",expand=True)
C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\2358179937.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado["Type"] = "leaf pulverized"
C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\2358179937.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado["Plot"]= df_filtrado["Plot"].str.replace("p","")

    Sample-ID       [C]%  δ13C (‰ v.s.V-PDB)             Type
78    p23-557   0.455530          -29.289590  leaf pulverized
80    p22-550   0.474114          -29.723659  leaf pulverized
95    p23-561  43.689971          -31.626469  leaf pulverized
96    p29-763  48.003020          -32.797394  leaf pulverized
97    p29-768  43.306540          -29.511927  leaf pulverized
..        ...        ...                 ...              ...
268  p60-8774  43.326518          -29.333433  leaf pulverized
269  p60-8763  43.478149          -28.901935  leaf pulverized
270  p60-8751  43.998552          -27.759220  leaf pulverized
271  p28-8738  43.841439          -32.261144  leaf pulverized
272  p60-8885  46.225205          -33.253234  leaf pulverized

[78 rows x 4 columns]

In [79]:

SEQ1= pd.read_excel("Andrea_bulk CN_2025.xlsx",sheet_name="SEQ1")
SEQ1["Year"] = 2006
SEQ2 = pd.read_excel("Andrea_bulk CN_2025.xlsx",sheet_name="SEQ2")
SEQ2["Year"] = 2006
SEQ4 = pd.read_excel("Andrea_bulk CN_2025.xlsx",sheet_name="SEQ4")
SEQ4["Year"] = 2025
SEQ5 = pd.read_excel("Andrea_bulk CN_2025.xlsx",sheet_name="SEQ5")
SEQ5["Year"] = 2025
SEQ7 = pd.read_excel("Andrea_bulk CN_2025.xlsx",sheet_name="SEQ7")
SEQ7["Year"] = 2006

bulk = pd.concat([SEQ1,SEQ2,SEQ4,SEQ5,SEQ7])
bulk = bulk.rename(columns={"certified values":"sample-ID", "Unnamed: 2":"[N]",
                            "Unnamed: 4":nameC_bulk,"Unnamed: 6":named15N,
                            "Unnamed: 8":named13C_bulk,"[C] in %":named13C_cellulose})


bulk[["Plot","TreeID","add"]] =bulk["sample-ID"].str.split("-",expand=True) #len 182
columns_drop = ["Unnamed: 0", "Unnamed: 3","Unnamed: 5","Unnamed: 7", "Unnamed: 9","Unnamed: 10","Unnamed: 11","Unnamed: 12"]
bulk = bulk.drop(columns=columns_drop)
patrones = ["p60", "p62", "p22","p23","p24","p28","p48","p50","p29"]
df_filtrado_bulk = bulk[bulk["sample-ID"].str.contains("|".join(patrones), na=False)]
df_filtrado_bulk = df_filtrado_bulk.drop(columns = {"add"})
df_filtrado_bulk = homogeneizar_ID(df_filtrado_bulk)
df_filtrado_bulk

,sample-ID,[N],[C_b]%,δ15N (‰ v.s. V-PDB),bulk_δ13C (‰ v.s.V-PDB),Year,Plot,TreeID,old_treeID,new_TreeID
18,p22-522,0.026297,0.413892,4.52,-30.8,2006,p22,522,522,NaN
19,p22-525,0.014931,0.449723,2.14,-30.33,2006,p22,525,525,NaN
20,p22-535,0.023597,0.473618,2.76,-31.05,2006,p22,535,535,NaN
21,p22-537,0.023649,0.48774,-0.98,-31.22,2006,p22,537,537,NaN
22,p22-538,0.021715,0.443533,1.37,-32.59,2006,p22,538,538,NaN
...,...,...,...,...,...,...,...,...,...,...
55,p29-777,0.020353,0.465026,0.910612,-30.928973,2006,p29,777,777,NaN
56,p29-779,0.027024,0.456031,4.883287,-32.268307,2006,p29,779,779,NaN
57,p29-781,0.030355,0.443805,1.769842,-33.762179,2006,p29,781,781,NaN
58,p29-792,0.017992,0.385438,1.274521,-33.113117,2006,p29,792,792,NaN
59,p29-793,0.025191,0.438924,3.417542,-32.618594,2006,p29,793,793,NaN

In [80]:
merged_cellulosa_bulk = pd.merge(df_filtrado, df_filtrado_bulk,left_on="Sample-ID", right_on="sample-ID",how= "outer")
len(merged_cellulosa_bulk) #82

merged_cellulosa_bulk["Sample-ID"] = merged_cellulosa_bulk["Sample-ID"].combine_first(merged_cellulosa_bulk["sample-ID"])#.to_excel("test.xlsx")
merged_cellulosa_bulk = merged_cellulosa_bulk.drop(columns={"TreeID","sample-ID"})
merged_cellulosa_bulk.head(5)

,Sample-ID,[C]%,δ13C (‰ v.s.V-PDB),Type,[N],[C_b]%,δ15N (‰ v.s. V-PDB),bulk_δ13C (‰ v.s.V-PDB),Year,Plot,old_treeID,new_TreeID
0,p23-557,0.455530,-29.289590,leaf pulverized,0.019124,0.485531,1.960678,-31.458731,2006.0,p23,557,NaN
1,p23-557,43.360479,-29.427788,leaf pulverized,0.019124,0.485531,1.960678,-31.458731,2006.0,p23,557,NaN
2,p22-550,0.474114,-29.723659,leaf pulverized,0.02523,0.465053,4.37,-30.31,2006.0,p22,550,NaN
3,p22-550,47.207712,-29.723923,leaf pulverized,0.02523,0.465053,4.37,-30.31,2006.0,p22,550,NaN
4,p23-561,43.689971,-31.626469,leaf pulverized,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Celulosa de muestras de herbario y muestras enero 2026.

In [81]:
cel2026 = pd.read_excel(r"C:\Users\selene.baez\Downloads\NAPO_preliminar\Results_isofys\Andrea-Cellulose-13C-202603.xlsx")
cel2026["Sample-ID"] = cel2026["Sample-ID"].replace({"3872":"jh-3872","3896":"jh-3896","3885":"jh-3885","jh3697":"jh-3697","jh3621":"jh3621"}) ### REVISAR
cel2026[["Plot","numeroCampo"]] = cel2026["Sample-ID"].str.split("-",expand=True) #aplica para los que sean herbario pero tambien saca los que no
cel2026["Plot"] = cel2026["Plot"].str.replace("p","")
cel2026.loc[cel2026["Plot"] != "jh", "Type"] = "leaf pulverized"
cel2026.loc[cel2026["Plot"] != "jh", "Year"] = 2025
cel2026.loc[cel2026["Plot"] == "jh", "Type"] = "leaf herbarium"
cel2026.loc[cel2026["Plot"] == "jh", "Year"] = 2006

cel2026["numeroCampo"] = cel2026["numeroCampo"].astype("float64")
cel2026 = cel2026.drop(columns={"nr of samples","Batch"})
cel2026 = cel2026.rename(columns={"[C] m/m in %":nameC_cellulose,"δ13C (‰ v.s. V-PDB)":named13C_cellulose})

In [82]:
### Cleaning of the new cellulose results.
#  
### work only with pulverized samples ####
pulv2026 = cel2026[cel2026["Type"] == "leaf pulverized"] ##99
pulv2026 [["Plot","new_TreeID"]] = pulv2026["Sample-ID"].str.split("-",expand=True)
pulv2026["Plot"]= pulv2026["Plot"].str.replace("p","") #homogeneizar
patrones = ["60", "62", "22","23","24","28","48","50","29"]
regex = r"p(" + "|".join(patrones) + r")\b"
pulv2026Gal = pulv2026[pulv2026["Sample-ID"].str.contains(regex, na=False)] #OK
    
### only working with samples 2006 jh herbarium ##
herb_2006 = cel2026[cel2026["Type"] == "leaf herbarium"] ##99
herb = pd.read_excel(r"C:\Users\selene.baez\Downloads\NAPO_preliminar\Jürgen herbarium\QCA_GOET.xlsx")
herb = herb[["numeroCampo","description"]] # se saca los numeros de los arboles
herb = herb.drop_duplicates(subset="numeroCampo")
herb_2006["numeroCampo"] = herb_2006["numeroCampo"].astype("float64")
herb["numeroCampo"] = herb["numeroCampo"].astype("float64")

cel2026_herb = pd.merge(herb_2006,herb,left_on="numeroCampo",right_on="numeroCampo", how ="left")
cel2026_herb[["Plot_","TreeID_herb"]]= cel2026_herb["description"].str.split("#",expand=True)
cel2026_herb[["old_treeID","comment","comment2"]]= cel2026_herb["TreeID_herb"].str.split(",",expand=True)
cel2026_herb["Plot"]= cel2026_herb["Plot_"].str.replace("plot","").combine_first(cel2026_herb["Plot"])
cel2026_herb = cel2026_herb.drop(columns={"comment","comment2","TreeID_herb"}) ### Plot that are JH look for them somewhere.

patrones = ["60", "62", "22","23","24","28","48","50","29"] #Galeras
#regex = r"p(" + "|".join(patrones) + r")\b"
herb_galeras = cel2026_herb[cel2026_herb["Plot"].str.contains("|".join(patrones), na=False)]

C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\3285264449.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pulv2026 [["Plot","new_TreeID"]] = pulv2026["Sample-ID"].str.split("-",expand=True)
C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\3285264449.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pulv2026 [["Plot","new_TreeID"]] = pulv2026["Sample-ID"].str.split("-",expand=True)
C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\3285264449.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pulv2026["Plot"]= pulv2026["Plot"].str.replace("p","") #homogeneizar
C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\3285264449.py:9: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  pulv2026Gal = pulv2026[pulv2026["Sample-ID"].str.contains(regex, na=False)] #OK
C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\3285264449.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  herb_2006["numeroCampo"] = herb_2006["numeroCampo"].astype("float64")

# Ultima placa de celulosa con multiples muestras
Miscelanea

In [83]:
mis2026 = pd.read_excel(r"C:\Users\selene.baez\Downloads\NAPO_preliminar\Results_isofys\Report 13C-pq4.xlsx")
#cel2026["Sample-ID"] = cel2026["Sample-ID"].replace({"3872":"jh-3872","3896":"jh-3896","3885":"jh-3885","jh3697":"jh-3697","jh3621":"jh3621"}) ### REVISAR
mis2026 = mis2026.rename(columns={"Sample ID":"Sample-ID"})#arriba todo con guion
mis2026 = mis2026.rename(columns={"[C] m/m":nameC_cellulose,"δ13C (‰ v.s. V-PDB)":named13C_cellulose})

patrones = ["60", "62", "20","22","23","24","28","48","50","29"]
regex = r"p(" + "|".join(patrones) + r")\b"
mis2026 = mis2026[mis2026["Sample-ID"].str.contains(regex, na=False)] #Filtremos solo Galeras
mis2026.loc[mis2026["Sample-ID"].str.contains("jh"), "Type"] = "leaf herbarium"
mis2026.loc[mis2026["Sample-ID"].str.contains("jh"), "Year"] = "2006"
mis2026.loc[~mis2026["Sample-ID"].str.contains("jh"), "Type"] = "leaf pulverized"

#separamos los resultados del herbario para añadir informacion
misjh = mis2026[mis2026["Type"]== "leaf herbarium"][["Sample-ID",nameC_cellulose,named13C_cellulose,"Type","Year"]]
misjh[["Type 2","Plot","numeroCampo"]]= misjh["Sample-ID"].str.split("-",expand=True)
misjh["numeroCampo"] = misjh["numeroCampo"].astype("float64")
misjh_herb = pd.merge(misjh,herb,left_on="numeroCampo",right_on="numeroCampo", how ="left")
misjh_herb["old_treeID"] = misjh_herb["description"].str.extract(r"#\s*(\d+)")
misjh_herb["Type 2"] = "Miscelanea" #para verificar q si funciona

#### separamos los de parcelas
mis_cel = mis2026[mis2026["Type"]== "leaf pulverized"][["Sample-ID",nameC_cellulose,named13C_cellulose,"Type"]]#Year, quiero revisar
mis_cel[["Plot","TreeID"]]= mis_cel["Sample-ID"].str.split("-",expand=True)
mis_cel #asignar  9 muestral manualmente los años. Creo que del 23 y 29 son del 2006 o cualquier otro año.
year_dict = {
    "p23-566": 2006,
    "p23-578": 2006,
    "p29-792": 2006,
    "p23-565": 2006,
    "p23-560": 2006,
    "p48-8666": 2025,
    "p48-3698": 2025,
    "p23-8980": 2025,
    "p28-8974":2025
}
mis_cel["Year"] = mis_cel["Sample-ID"].map(year_dict)
mis_cel.loc[mis_cel["Year"] == 2006, "old_treeID"] = mis_cel["TreeID"]
mis_cel.loc[mis_cel["Year"] == 2025, "new_TreeID"] = mis_cel["TreeID"]
mis_cel ### FALTAN MUESTRS DEL PLOT 20

C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\2065748477.py:8: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mis2026 = mis2026[mis2026["Sample-ID"].str.contains(regex, na=False)] #Filtremos solo Galeras

,Sample-ID,[C]%,δ13C (‰ v.s.V-PDB),Type,Plot,TreeID,Year,old_treeID,new_TreeID
10,p23-566,0.4499,-32.80,leaf pulverized,p23,566,2006.0,566,NaN
12,p23-578,0.3496,-30.42,leaf pulverized,p23,578,2006.0,578,NaN
14,p29-792,0.3766,-32.34,leaf pulverized,p29,792,2006.0,792,NaN
15,p48-8666,0.4249,-31.49,leaf pulverized,p48,8666,2025.0,NaN,8666
22,p23-565,0.4368,-32.44,leaf pulverized,p23,565,2006.0,565,NaN
24,p48-3698,0.4193,-27.79,leaf pulverized,p48,3698,2025.0,NaN,3698
75,p23-8980,0.2728,-28.17,leaf pulverized,p23,8980,2025.0,NaN,8980
80,p20-495,0.4012,-29.90,leaf pulverized,p20,495,NaN,NaN,NaN
82,p28-8974,0.4054,-29.37,leaf pulverized,p28,8974,2025.0,NaN,8974
85,p23-560,0.3961,-30.10,leaf pulverized,p23,560,2006.0,560,NaN
86,p20-489,0.4672,-29.51,leaf pulverized,p20,489,NaN,NaN,NaN

In [84]:
#### con la miscelanea ###
results_2026 = pd.concat([herb_galeras,pulv2026Gal,misjh_herb,mis_cel])

results_2026 = results_2026.drop(columns={"Plot_","TreeID"})

In [85]:
unido = pd.concat([merged_cellulosa_bulk,results_2026])
unido["Plot"]= unido["Plot"].str.replace("p","")
unido#.to_excel("unido.xlsx")

,Sample-ID,[C]%,δ13C (‰ v.s.V-PDB),Type,[N],[C_b]%,δ15N (‰ v.s. V-PDB),bulk_δ13C (‰ v.s.V-PDB),Year,Plot,old_treeID,new_TreeID,numeroCampo,description,Type 2
0,p23-557,0.455530,-29.289590,leaf pulverized,0.019124,0.485531,1.960678,-31.458731,2006.0,23,557,NaN,NaN,NaN,NaN
1,p23-557,43.360479,-29.427788,leaf pulverized,0.019124,0.485531,1.960678,-31.458731,2006.0,23,557,NaN,NaN,NaN,NaN
2,p22-550,0.474114,-29.723659,leaf pulverized,0.02523,0.465053,4.37,-30.31,2006.0,22,550,NaN,NaN,NaN,NaN
3,p22-550,47.207712,-29.723923,leaf pulverized,0.02523,0.465053,4.37,-30.31,2006.0,22,550,NaN,NaN,NaN,NaN
4,p23-561,43.689971,-31.626469,leaf pulverized,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,p23-8980,0.272800,-28.170000,leaf pulverized,NaN,NaN,NaN,NaN,2025.0,23,NaN,8980,NaN,NaN,NaN
80,p20-495,0.401200,-29.900000,leaf pulverized,NaN,NaN,NaN,NaN,NaN,20,NaN,NaN,NaN,NaN,NaN
82,p28-8974,0.405400,-29.370000,leaf pulverized,NaN,NaN,NaN,NaN,2025.0,28,NaN,8974,NaN,NaN,NaN
85,p23-560,0.396100,-30.100000,leaf pulverized,NaN,NaN,NaN,NaN,2006.0,23,560,NaN,NaN,NaN,NaN
86,p20-489,0.467200,-29.510000,leaf pulverized,NaN,NaN,NaN,NaN,NaN,20,NaN,NaN,NaN,NaN,NaN

### Faltan los resultados del bulk

In [86]:
herb = (
    pd.read_excel(r"C:\Users\selene.baez\Downloads\NAPO_preliminar\Jürgen herbarium\QCA_GOET.xlsx")
    [["numeroCampo", "description"]]
    .drop_duplicates(subset="numeroCampo")
 )
bulk_2026 = pd.read_excel(r"C:\Users\selene.baez\Downloads\NAPO_preliminar\Results_isofys\bulk_listado_2026.xlsx")##corregimos despues
bulk_2026[nameC_bulk] = "waiting"
bulk_2026[named13C_bulk] = "waiting"
bulk_2026[named15N] = "waiting"

In [87]:
import limpiar_bulk
%run limpiar_bulk

bulk_2026 = limpiar_bulk(bulk_2026,herb)
bulk_2026 #HELP deberia unir con resultados de la celulosa y listo

C:\Users\selene.baez\Downloads\NAPO_preliminar\Galeras\limpiar_bulk.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  herb_2006[["Type","Plot","numeroCampo"]] = herb_2006["Sample-ID"].str.split("-",expand=True)
C:\Users\selene.baez\Downloads\NAPO_preliminar\Galeras\limpiar_bulk.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  herb_2006[["Type","Plot","numeroCampo"]] = herb_2006["Sample-ID"].str.split("-",expand=True)
C:\Users\selene.baez\Downloads\NAPO_preliminar\Galeras\limpiar_bulk.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  herb_2006[["Type","Plot","numeroCampo"]] = herb_2006["Sample-ID"].str.split("-",expand=True)
C:\Users\selene.baez\Downloads\NAPO_preliminar\Galeras\limpiar_bulk.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  herb_2006["numeroCampo"]=herb_2006["numeroCampo"].combine_first(herb_2006["Plot"])
C:\Users\selene.baez\Downloads\NAPO_preliminar\Galeras\limpiar_bulk.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  herb_galeras["Year"] = 2006
C:\Users\selene.baez\Downloads\NAPO_preliminar\Galeras\limpiar_bulk.py:31: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  pulv2026 = pulv2026[pulv2026["Sample-ID"].str.contains(regex, na=False)] #Solo los que ya tienen plot aqui son del 2025

,Sample-ID,Nutrients,[C_b]%,bulk_δ13C (‰ v.s.V-PDB),δ15N (‰ v.s. V-PDB),Type,numeroCampo,description,Plot,old_treeID,Year,new_TreeID
0,jh-p62-2529,Waiting,waiting,waiting,waiting,jh,2529.0,"plot 62 #1882, flower buds",62,1882,2006,NaN
1,jh-p62-3611,Waiting,waiting,waiting,waiting,jh,3611.0,"plot 62#1901, old fruits",62,1901,2006,NaN
2,jh-p28-3579,Waiting,waiting,waiting,waiting,jh,3579.0,plot 28#719,28,719,2006,NaN
3,jh-p62-3595,Waiting,waiting,waiting,waiting,jh,3595.0,"plot 62#1872, fruits",62,1872,2006,NaN
4,jh-p60-3659,Waiting,waiting,waiting,waiting,jh,3659.0,plot 60#1804,60,1804,2006,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
117,p62-8909,Waiting,waiting,waiting,waiting,NaN,NaN,NaN,p62,NaN,2025,8909
118,p62-8935,Waiting,waiting,waiting,waiting,NaN,NaN,NaN,p62,NaN,2025,8935
119,p62-8904,Waiting,waiting,waiting,waiting,NaN,NaN,NaN,p62,NaN,2025,8904
120,p23-561,Waiting,waiting,waiting,waiting,NaN,NaN,NaN,p23,NaN,2025,561
121,p23-559,Waiting,waiting,waiting,waiting,NaN,NaN,NaN,p23,NaN,2025,559

In [88]:
#Samples that were getting lost with the filter
df = unido
df.loc[df["Sample-ID"] == "p23-561", ["Year","Plot","old_treeID"]] = [2006,"p23",561]
df.loc[df["Sample-ID"] == "p28-8878", ["Year","Plot","new_TreeID"]] = [2025,"p28",8878]
df.loc[df["Sample-ID"] == "p60-8885", ["Year","Plot","new_TreeID"]] = [2025,"p60",8885]
df.loc[df["Sample-ID"] == "p20-495", ["Year","Plot","old_treeID"]] = [2006,"p20",495]
df.loc[df["Sample-ID"] == "p20-489", ["Year","Plot","old_treeID"]] = [2006,"p20",489]
#df["Sample-ID"] = df["Sample ID"].combine_first(df["sample-ID"])
df.to_excel("test.xlsx")

# Unir con la base de datos completa para añadir informacion adicional

In [89]:
### HELP: USAR BASE GRANDE O RASGOS. Base grande eliminar los x y y de los datos para evitar problemas.
base_grande = pd.read_excel(r"\Users\selene.baez\Downloads\NAPO_preliminar\Galeras\Base_Galeras_vK.xlsx")
base_grande = base_grande[["Plot","treeID","new ID 2024","family","JH herbarium collections", "genus","species"]]
base_grande = base_grande[~base_grande["treeID"].isin(["x", "y"])]
base_grande["treeID"] = base_grande["treeID"].replace("", np.nan)
base_grande["treeID"] = base_grande["treeID"].astype("Float64")
base_grande = base_grande.rename(columns={"treeID":"old_treeID","new ID 2024":"new_TreeID"})
base_grande.head(3)

,Plot,old_treeID,new_TreeID,family,JH herbarium collections,genus,species
0,20,471.0,NaN,Rubiaceae,1995,Randia,NaN
1,20,472.0,NaN,Rubiaceae,NaN,Randia,NaN
2,20,473.0,NaN,Burseraceae,1982,Dacryodes,aff cupularis

In [90]:

df_filtrado = df
df_filtrado["Year"] = df_filtrado["Year"].astype("Float64")

df_2006 = df_filtrado[df_filtrado["Year"] == 2006.0]
df_2006 = df_2006.drop(columns= {"new_TreeID","numeroCampo","Plot"})#no ayuda mucho aqui el new por eso elimino, esta vacio ynumero de campo se duplica pero sirve para verificar
print(len(df_2006)) #120
df_2006["old_treeID"] = df_2006["old_treeID"].astype("Float64")
merge_2006 = pd.merge(df_2006,base_grande,on= "old_treeID", how = "left") #left. Prioridad a los isotopos 
merge_2006.to_excel("2006.xlsx")

120

In [91]:

df_2025 = df_filtrado[df_filtrado["Year"] == 2025.0]
df_2025["new_TreeID"] = df_2025["new_TreeID"].astype("Float64")
df_2025 = df_2025.drop(columns= {"old_treeID","numeroCampo","Plot"})#numero de campo se duplica pero sirve para verificar

print(len(df_2025)) #83

base_grande["new_TreeID"] = base_grande["new_TreeID"].astype("Float64")
merge_2025 = pd.merge(df_2025,base_grande, on="new_TreeID", how = "left") #left. Prioridad a los isotopos 
merge_2025.to_excel("2025.xlsx")
###

83

C:\Users\selene.baez\AppData\Local\Temp\ipykernel_26452\2550729951.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2025["new_TreeID"] = df_2025["new_TreeID"].astype("Float64")

# Unir las celdas 2006 y 2025

In [92]:

all = pd.concat([merge_2006,merge_2025])
all.to_excel("Galeras_cellulose.xlsx")

In [ ]:
len(all) #duplicados etc, falta arreglar unidades.

206